name: Continuous Integration
on: push
jobs:
  run_code_checks:
    runs_on: ubuntu-latest
    steps:
      - name: check version of go
        run: |
          sudo lsb_release -a
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test
