name: Continuous Integration
on: push
jobs:
  run_code_checks:
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DYNAMODB_TABLE_NAME: ${{secrets.DYNAMODB_TABLE_NAME}}
    runs-on: ubuntu-latest
    steps:
      - name: check version of go
        run: |
          sudo lsb_release -a
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: check for vars
        run: echo $AWS_REGION
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test ./cmd/
